count = 0
n1 = float(input())
if(n1 > 0):
  count += 1
n2 = float(input())
if(n2 > 0):
  count += 1
n3 = float(input())
if(n3 > 0):
  count += 1
n4 = float(input())
if(n4 > 0):
  count += 1
n5 = float(input())
if(n5 > 0):
  count += 1
n6 = float(input())
if(n6 > 0):
  count += 1
print("{n} valores positivos".format(n = count))